import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const Color kButtonColor = Color(0xFF2A3B5D);
const Color kPrimaryColor = Color(0xff29ABE2);
const Color kContainerColor = Color(0xffD3E5F9);
const Color kH2Color = Color(0xff19303E);
const Color kDescriptionColor = Color(0xff6A6A6A);
const Color kHintTextColor = Color(0xffB7B7B7);
const Color kTextFieldFillColor = Color(0xffFCFCFC);
const Color kBoxColor = Color(0xffF2F2FF);
const Color kUnselectedItemColor = Color(0xffA2A2A2);
const Color kNotificationDotColor = Color(0xffA7F388);
const Color kButtonBGColor = Color(0xffFCEAEA);
const Color kDeleteBackgroundColor = Color(0xffFFE4E4);
const Color kWhiteColor = Color(0xffffffff);
const Color kBorderColor = Color(0xffD9D9D9);
const Color kNameColor = Color(0xff4A4B4D);
const Color kCheckBackgroundColor = Color(0xffDEE1FF);
const Color kSendChatColor = Color(0xffEEF7F9);
const Color kReceiveChatColor = Color(0xffF9EEEE);
const Color kRatingStarColor = Colors.amber;
